---
# defaults file for intellij

intellij_download_mirror: https://download.jetbrains.com/idea
intellij_version: 2018.1.4
intellij_edition: community

intellij_download_url: "{{ intellij_download_mirror }}/ideaIC-{{ intellij_version }}.tar.gz"

intellij_install_dir: "~/intellij-{{ intellij_version }}"
intellij_install_dir_symlink: "~/intellij"

intellij_plugin_download_mirror: "https://plugins.jetbrains.com/plugin/download?updateId="
intellij_plugins:
  - 44635   # Material Theme
